export const recommendListdata = [
  {
    meetingId: "M2025022103",
    title: "普现急速摸卡流",
    views: "1381",
    duration: "1:30:00",
    cover: "/static/images/meeting1.jpg",
  },
  {
    meetingId: "M2025022102",
    title: "从来如此，便对么？",
    views: "302.1万",
    duration: "2:59",
    cover: "/static/images/meeting2.jpg",
  },
  {
    meetingId: "M2025022104",
    title: "STM32智能大棚项目",
    views: "2078",
    duration: "7:31",
    cover: "/static/images/meeting3.jpg",
  },
  {
    meetingId: "4",
    title: "洛克王国开发进度分享",
    views: "293.2万",
    duration: "1:49",
    cover: "/static/images/meeting4.jpg",
  },
  {
    meetingId: "5",
    title: "2024前端技术分享会",
    views: "5.2万",
    duration: "45:21",
    cover: "/static/images/meeting5.jpg",
  },
  {
    meetingId: "6",
    title: "AI助手开发经验分享",
    views: "12.5万",
    duration: "32:15",
    cover: "/static/images/meeting6.jpg",
  },
  {
    meetingId: "7",
    title: "区块链技术应用实践",
    views: "8.9万",
    duration: "1:15:00",
    cover: "/static/images/meeting7.jpg",
  },
  {
    meetingId: "8",
    title: "移动应用性能优化",
    views: "6.7万",
    duration: "55:30",
    cover: "/static/images/meeting8.jpg",
  },
  {
    meetingId: "9",
    title: "云原生架构设计",
    views: "15.3万",
    duration: "1:20:00",
    cover: "/static/images/meeting9.jpg",
  },
  {
    meetingId: "10",
    title: "微服务部署与运维",
    views: "9.4万",
    duration: "48:25",
    cover: "/static/images/meeting10.jpg",
  },
  {
    meetingId: "11",
    title: "大数据分析与应用",
    views: "3.6万",
    duration: "40:12",
    cover: "/static/images/meeting11.jpg",
  },
  {
    meetingId: "12",
    title: "物联网安全挑战",
    views: "2.1万",
    duration: "33:45",
    cover: "/static/images/meeting12.jpg",
  },
  {
    meetingId: "13",
    title: "人工智能在医疗领域的应用",
    views: "4.8万",
    duration: "50:00",
    cover: "/static/images/meeting13.jpg",
  },
  {
    meetingId: "14",
    title: "5G网络技术解析",
    views: "6.3万",
    duration: "42:19",
    cover: "/static/images/meeting14.jpg",
  },
  {
    meetingId: "15",
    title: "虚拟现实技术发展",
    views: "7.2万",
    duration: "38:50",
    cover: "/static/images/meeting15.jpg",
  },
  {
    meetingId: "16",
    title: "深度学习与神经网络",
    views: "8.1万",
    duration: "1:05:00",
    cover: "/static/images/meeting16.jpg",
  },
  {
    meetingId: "17",
    title: "边缘计算的未来",
    views: "5.5万",
    duration: "47:20",
    cover: "/static/images/meeting17.jpg",
  },
  {
    meetingId: "18",
    title: "量子计算原理初探",
    views: "3.9万",
    duration: "44:11",
    cover: "/static/images/meeting18.jpg",
  },
  {
    meetingId: "19",
    title: "智能合约与去中心化应用",
    views: "4.7万",
    duration: "39:40",
    cover: "/static/images/meeting19.jpg",
  },
  {
    meetingId: "20",
    title: "网络安全防护策略",
    views: "6.8万",
    duration: "51:30",
    cover: "/static/images/meeting20.jpg",
  },
  {
    meetingId: "21",
    title: "机器学习基础教程",
    views: "8.2万",
    duration: "1:12:00",
    cover: "/static/images/meeting21.jpg",
  },
  {
    meetingId: "22",
    title: "前端框架比较分析",
    views: "5.1万",
    duration: "35:40",
    cover: "/static/images/meeting22.jpg",
  },
  {
    meetingId: "23",
    title: "云计算平台搭建与实践",
    views: "7.3万",
    duration: "42:10",
    cover: "/static/images/meeting23.jpg",
  },
  {
    meetingId: "24",
    title: "深度学习在图像识别中的应用",
    views: "6.4万",
    duration: "38:25",
    cover: "/static/images/meeting24.jpg",
  },
  {
    meetingId: "25",
    title: "大数据时代的商业智能",
    views: "9.9万",
    duration: "45:50",
    cover: "/static/images/meeting25.jpg",
  },
  {
    meetingId: "26",
    title: "物联网与智能硬件",
    views: "4.5万",
    duration: "40:15",
    cover: "/static/images/meeting26.jpg",
  },
  {
    meetingId: "27",
    title: "人工智能在游戏开发中的应用",
    views: "3.8万",
    duration: "36:50",
    cover: "/static/images/meeting27.jpg",
  },
  {
    meetingId: "28",
    title: "区块链与数字货币",
    views: "5.7万",
    duration: "39:40",
    cover: "/static/images/meeting28.jpg",
  },
  {
    meetingId: "29",
    title: "软件定义网络架构",
    views: "6.2万",
    duration: "41:20",
    cover: "/static/images/meeting29.jpg",
  },
  {
    meetingId: "30",
    title: "云计算与大数据分析",
    views: "7.9万",
    duration: "43:30",
    cover: "/static/images/meeting30.jpg",
  },
];

export const swiperListdata = [
  {
    meetingId: "122",
    image: "/src/static/images/swiper/1.jpg",
    title: "2024技术峰会",
  },
  {
    meetingId: "221",
    image: "/src/static/images/swiper/2.jpg",
    title: "AI发展论坛",
  },
  {
    meetingId: "3123",
    image: "/src/static/images/swiper/3.jpg",
    title: "创新创业大会",
  },
  {
    meetingId: "12323",
    image: "/src/static/images/swiper/4.png",
    title: "前沿科技",
  },
  {
    meetingId: "123123",
    image: "/src/static/images/swiper/5.png",
    title: "人工智能",
  },
];
